-- Supabase/PostgreSQL schema for World2 · Agent 平行世界.
-- Paste this file into Supabase SQL Editor, or run it with psql.
-- JSON-like fields are intentionally kept as text because the current Python
-- code stores and parses JSON strings with json.dumps/json.loads.

create table if not exists residents (
    id integer generated by default as identity primary key,
    name text not null unique,
    role text not null,
    personality text not null,
    goal text not null,
    money integer not null default 100,
    location text not null,
    created_at text not null default current_timestamp
);

create table if not exists agent_profiles (
    resident_id integer primary key references residents(id) on delete cascade,
    gender text not null,
    avatar_style text not null,
    avatar_image text not null default '',
    hierarchy_level integer not null default 1,
    organization text not null default '学生',
    skills text not null default '{}',
    strategy text not null default '{}',
    energy integer not null default 80,
    time_budget integer not null default 100,
    mood text not null default '平稳',
    current_task text not null default '适应校园生活',
    schedule text not null default '[]',
    perception text not null default '{}'
);

create table if not exists inventory (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    item_name text not null,
    quantity integer not null default 0,
    unique(resident_id, item_name)
);

create table if not exists transactions (
    id integer generated by default as identity primary key,
    buyer_id integer not null references residents(id) on delete cascade,
    seller_id integer not null references residents(id) on delete cascade,
    item_name text not null,
    quantity integer not null,
    unit_price integer not null,
    total_price integer not null,
    created_at text not null default current_timestamp
);

create table if not exists relationships (
    from_resident_id integer not null references residents(id) on delete cascade,
    to_resident_id integer not null references residents(id) on delete cascade,
    score integer not null default 0,
    notes text not null default '',
    primary key (from_resident_id, to_resident_id)
);

create table if not exists policies (
    id integer generated by default as identity primary key,
    title text not null,
    description text not null,
    proposer_id integer not null references residents(id) on delete cascade,
    status text not null default 'voting',
    yes_votes integer not null default 0,
    no_votes integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists city_events (
    id integer generated by default as identity primary key,
    day integer not null default 1,
    event_type text not null,
    description text not null,
    created_at text not null default current_timestamp
);

create table if not exists memories (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    day integer not null default 1,
    content text not null,
    importance integer not null default 1,
    memory_type text not null default 'episodic',
    tags text not null default '',
    source text not null default 'action',
    last_accessed_at text not null default '',
    access_count integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists simulation_state (
    key text primary key,
    value text not null
);

create table if not exists agent_learning (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    day integer not null default 1,
    action text not null,
    outcome text not null,
    score_delta integer not null default 0,
    lesson text not null,
    created_at text not null default current_timestamp
);

create table if not exists collaborations (
    id integer generated by default as identity primary key,
    title text not null,
    leader_id integer not null references residents(id) on delete cascade,
    member_ids text not null default '[]',
    goal text not null,
    status text not null default 'active',
    score integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists competitions (
    id integer generated by default as identity primary key,
    title text not null,
    participant_ids text not null default '[]',
    metric text not null,
    winner_id integer references residents(id) on delete set null,
    result text not null,
    created_at text not null default current_timestamp
);

create table if not exists campus_state (
    day integer primary key,
    weather text not null default '晴',
    semester_stage text not null default '平时周',
    time_slot text not null default '上午',
    weekday text not null default '周一',
    temperature integer not null default 24,
    rainfall integer not null default 0,
    weather_source text not null default 'simulation',
    weather_observed_at text not null default '',
    real_date text not null default '',
    real_time text not null default '',
    time_source text not null default 'simulation',
    exam_pressure integer not null default 35,
    assignment_pressure integer not null default 40,
    study_atmosphere integer not null default 60,
    activity_heat integer not null default 50,
    event_name text not null default '社团招新',
    event_intensity integer not null default 50,
    campus_flow integer not null default 55,
    classroom_crowd integer not null default 55,
    canteen_crowd integer not null default 50,
    library_crowd integer not null default 45,
    dorm_crowd integer not null default 45,
    playground_crowd integer not null default 40,
    commercial_crowd integer not null default 50,
    traffic_status text not null default '正常',
    network_status text not null default '稳定',
    safety_level integer not null default 90,
    resource_pressure integer not null default 45,
    campus_mood text not null default '平稳',
    consumption_index real not null default 1.0,
    created_at text not null default current_timestamp
);

create table if not exists campus_spaces (
    code text primary key,
    name text not null,
    location text not null unique,
    capacity integer not null,
    open_hour integer not null,
    close_hour integer not null,
    status text not null default '开放',
    crowd_field text not null,
    purpose text not null,
    updated_at text not null default current_timestamp
);

create table if not exists campus_events (
    id integer generated by default as identity primary key,
    day integer not null,
    title text not null,
    event_type text not null,
    intensity integer not null default 50,
    target_spaces text not null default '[]',
    effects text not null default '{}',
    status text not null default 'active',
    created_at text not null default current_timestamp,
    resolved_at text
);

create table if not exists agent_news_posts (
    id integer generated by default as identity primary key,
    day integer not null,
    resident_id integer not null references residents(id) on delete cascade,
    tick_id integer,
    source_slot text not null default '',
    source_event_id integer,
    news_value integer not null default 50,
    headline text not null,
    content text not null,
    created_at text not null default current_timestamp,
    unique(day, resident_id)
);

create table if not exists external_information (
    id integer generated by default as identity primary key,
    title text not null unique,
    summary text not null,
    source_name text not null,
    source_url text not null default '',
    category text not null default 'general',
    relevance integer not null default 50,
    published_at text not null default '',
    created_at text not null default current_timestamp
);

create table if not exists agent_information (
    information_id integer not null references external_information(id) on delete cascade,
    resident_id integer not null references residents(id) on delete cascade,
    channel text not null,
    relevance integer not null default 50,
    credibility integer not null default 80,
    distortion_note text not null default '',
    source_resident_id integer references residents(id) on delete set null,
    received_at text not null default current_timestamp,
    primary key (information_id, resident_id)
);

create table if not exists relationship_dynamics (
    from_resident_id integer not null references residents(id) on delete cascade,
    to_resident_id integer not null references residents(id) on delete cascade,
    affinity integer not null default 50,
    trust integer not null default 50,
    cooperation integer not null default 50,
    competition integer not null default 0,
    conflict integer not null default 0,
    tension integer not null default 0,
    interaction_count integer not null default 0,
    last_day integer not null default 1,
    primary key (from_resident_id, to_resident_id)
);

create table if not exists long_term_goals (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    title text not null,
    category text not null default 'general',
    progress integer not null default 0,
    target_progress integer not null default 100,
    deadline_day integer not null default 14,
    status text not null default 'active',
    last_update_day integer not null default 1,
    created_at text not null default current_timestamp,
    completed_at text
);

create table if not exists group_goals (
    id integer generated by default as identity primary key,
    name text not null,
    group_type text not null default '临时小组',
    leader_id integer not null references residents(id) on delete cascade,
    member_ids text not null default '[]',
    roles text not null default '{}',
    shared_goal text not null,
    progress integer not null default 0,
    target_progress integer not null default 100,
    deadline_day integer not null default 14,
    status text not null default 'active',
    current_plan text not null default '',
    created_at text not null default current_timestamp
);

create table if not exists campus_organizations (
    id integer generated by default as identity primary key,
    name text not null unique,
    organization_type text not null,
    goal text not null,
    budget integer not null default 1000,
    resources text not null default '{}',
    schedule text not null default '[]',
    status text not null default 'active',
    created_at text not null default current_timestamp
);

create table if not exists agent_goals (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    parent_goal_id integer references agent_goals(id) on delete set null,
    legacy_long_term_goal_id integer unique references long_term_goals(id) on delete set null,
    horizon text not null default 'medium',
    title text not null,
    description text not null default '',
    category text not null default 'general',
    source text not null default 'self',
    priority integer not null default 50,
    commitment integer not null default 50,
    expected_utility integer not null default 50,
    feasibility integer not null default 50,
    uncertainty integer not null default 30,
    deadline_at text not null default '',
    status text not null default 'active',
    progress integer not null default 0,
    visibility text not null default 'private',
    created_day integer not null default 1,
    last_reviewed_day integer not null default 1,
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp,
    completed_at text
);

create table if not exists goal_dependencies (
    id integer generated by default as identity primary key,
    goal_id integer not null references agent_goals(id) on delete cascade,
    related_goal_id integer not null references agent_goals(id) on delete cascade,
    relationship_type text not null default 'supports',
    strength integer not null default 50,
    explanation text not null default '',
    created_at text not null default current_timestamp,
    unique(goal_id, related_goal_id, relationship_type)
);

create table if not exists goal_revisions (
    id integer generated by default as identity primary key,
    goal_id integer not null references agent_goals(id) on delete cascade,
    resident_id integer not null references residents(id) on delete cascade,
    day integer not null default 1,
    tick_id integer,
    revision_type text not null,
    before_json text not null default '{}',
    after_json text not null default '{}',
    reason text not null default '',
    trigger_type text not null default 'reflection',
    evidence_json text not null default '{}',
    created_at text not null default current_timestamp
);

create table if not exists agent_commitments (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    goal_id integer references agent_goals(id) on delete set null,
    counterparty_resident_id integer references residents(id) on delete set null,
    organization_id integer,
    commitment_type text not null default 'personal',
    title text not null,
    start_at text not null default '',
    due_at text not null default '',
    status text not null default 'active',
    importance integer not null default 50,
    flexibility integer not null default 50,
    visibility text not null default 'private',
    source_event_id integer,
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists plan_outcomes (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    plan_id integer,
    long_goal_id integer references agent_goals(id) on delete set null,
    medium_goal_id integer references agent_goals(id) on delete set null,
    short_goal_id integer references agent_goals(id) on delete set null,
    tick_id integer,
    day integer not null default 1,
    step_key text not null default '',
    planned_json text not null default '{}',
    actual_json text not null default '{}',
    adherence text not null default 'unknown',
    deviation_type text not null default '',
    deviation_reason text not null default '',
    outcome_summary text not null default '',
    progress_delta integer not null default 0,
    evidence_json text not null default '{}',
    created_at text not null default current_timestamp
);

create table if not exists trajectory_episodes (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    parent_episode_id integer references trajectory_episodes(id) on delete set null,
    goal_id integer references agent_goals(id) on delete set null,
    horizon text not null default 'short',
    episode_type text not null default 'activity',
    title text not null,
    start_at text not null,
    end_at text not null default '',
    status text not null default 'active',
    planned_summary text not null default '',
    actual_summary text not null default '',
    outcome_summary text not null default '',
    evidence_json text not null default '{}',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists organization_members (
    organization_id integer not null references campus_organizations(id) on delete cascade,
    resident_id integer not null references residents(id) on delete cascade,
    member_role text not null default 'member',
    joined_day integer not null default 1,
    status text not null default 'active',
    primary key (organization_id, resident_id)
);

create table if not exists simulation_action_logs (
    id integer generated by default as identity primary key,
    day integer not null,
    resident_id integer not null references residents(id) on delete cascade,
    perception text not null default '{}',
    retrieved_memories text not null default '[]',
    decision text not null default '{}',
    execution text not null default '{}',
    environment_feedback text not null default '{}',
    state_before text not null default '{}',
    state_after text not null default '{}',
    created_at text not null default current_timestamp
);

create table if not exists relationship_change_events (
    id integer generated by default as identity primary key,
    day integer not null default 1,
    tick_id integer,
    event_id integer,
    from_resident_id integer not null references residents(id) on delete cascade,
    to_resident_id integer not null references residents(id) on delete cascade,
    interaction text not null default '',
    reason text not null default '',
    affinity_before integer not null default 50,
    affinity_after integer not null default 50,
    trust_before integer not null default 50,
    trust_after integer not null default 50,
    cooperation_before integer not null default 50,
    cooperation_after integer not null default 50,
    competition_before integer not null default 0,
    competition_after integer not null default 0,
    conflict_before integer not null default 0,
    conflict_after integer not null default 0,
    created_at text not null default current_timestamp
);

create table if not exists social_interaction_events (
    id integer generated by default as identity primary key,
    day integer not null default 1,
    tick_id integer,
    world_event_id integer,
    relationship_change_event_id integer,
    actor_resident_id integer not null references residents(id) on delete cascade,
    target_resident_id integer references residents(id) on delete set null,
    participants_json text not null default '[]',
    location text not null default '',
    interaction_type text not null default 'interaction',
    interaction_channel text not null default 'in_person',
    intensity integer not null default 50,
    valence integer not null default 0,
    visibility text not null default 'local',
    disclosure_state text not null default 'ordinary',
    resource_context text not null default '',
    institution_context text not null default '',
    observer_summary text not null default '',
    evidence_json text not null default '{}',
    created_at text not null default current_timestamp
);

create table if not exists social_relation_interpretations (
    id integer generated by default as identity primary key,
    day integer not null default 1,
    tick_id integer,
    from_resident_id integer not null references residents(id) on delete cascade,
    to_resident_id integer not null references residents(id) on delete cascade,
    perspective text not null default 'system_researcher',
    current_label text not null default '未形成稳定解释',
    label_confidence integer not null default 20,
    candidate_labels_json text not null default '[]',
    evidence_json text not null default '[]',
    metrics_json text not null default '{}',
    interpretation_boundary text not null default '',
    created_at text not null default current_timestamp
);

create table if not exists social_beliefs (
    id integer generated by default as identity primary key,
    day integer not null default 1,
    tick_id integer,
    subject_resident_id integer not null references residents(id) on delete cascade,
    object_type text not null default 'relationship',
    object_resident_id integer references residents(id) on delete set null,
    related_resident_id integer references residents(id) on delete set null,
    belief_type text not null default 'knows',
    belief_summary text not null default '',
    confidence integer not null default 50,
    visibility text not null default 'private',
    source_event_id integer,
    created_at text not null default current_timestamp
);

create index if not exists idx_social_interaction_events_day on social_interaction_events(day);
create index if not exists idx_social_interaction_events_actor_day on social_interaction_events(actor_resident_id, day);
create index if not exists idx_social_interaction_events_target_day on social_interaction_events(target_resident_id, day);
create index if not exists idx_social_interaction_events_type on social_interaction_events(interaction_type);
create index if not exists idx_social_relation_interpretations_pair_day on social_relation_interpretations(from_resident_id, to_resident_id, day);
create index if not exists idx_social_relation_interpretations_label on social_relation_interpretations(current_label);
create index if not exists idx_social_beliefs_subject_day on social_beliefs(subject_resident_id, day);

create table if not exists world_runtime (
    id integer primary key,
    status text not null default 'paused',
    world_timezone text not null default 'Asia/Shanghai',
    world_time text not null default '',
    tick_interval_seconds integer not null default 60,
    agents_per_tick integer not null default 3,
    daily_auto_model_budget integer not null default 500,
    auto_model_calls_used integer not null default 0,
    budget_date text not null default '',
    current_agent_cursor integer not null default 0,
    last_tick_started_at text not null default '',
    last_tick_completed_at text not null default '',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists world_ticks (
    id integer generated by default as identity primary key,
    tick_index integer not null,
    world_time text not null,
    day integer not null,
    slot text not null,
    reason text not null default 'background',
    status text not null default 'running',
    processed_agents integer not null default 0,
    failed_agents integer not null default 0,
    error_message text not null default '',
    started_at text not null default current_timestamp,
    completed_at text
);

create table if not exists world_event_stream (
    id integer generated by default as identity primary key,
    tick_id integer references world_ticks(id) on delete set null,
    day integer not null,
    slot text not null,
    event_type text not null,
    resident_id integer references residents(id) on delete set null,
    location text not null default '',
    title text not null,
    content text not null,
    payload text not null default '{}',
    created_at text not null default current_timestamp
);

create table if not exists agent_action_plans (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    window_start text not null,
    window_end text not null,
    plan_json text not null default '{}',
    model_name text not null default 'rule-based-v1',
    prompt_version text not null default 'world-runtime-v1',
    status text not null default 'active',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp,
    unique(resident_id, window_start)
);

create table if not exists observer_sessions (
    id integer generated by default as identity primary key,
    user_id text not null default 'anonymous',
    session_type text not null default 'observer',
    focused_resident_id integer references residents(id) on delete set null,
    focused_location text not null default '',
    started_at text not null default current_timestamp,
    last_seen_at text not null default current_timestamp
);

create table if not exists participant_actions (
    id integer generated by default as identity primary key,
    user_id text not null default 'anonymous',
    action_type text not null,
    target_type text not null default '',
    target_id text not null default '',
    payload text not null default '{}',
    status text not null default 'queued',
    created_at text not null default current_timestamp
);

create table if not exists model_call_logs (
    id integer generated by default as identity primary key,
    trigger_type text not null,
    resident_id integer references residents(id) on delete set null,
    related_event_id integer references world_event_stream(id) on delete set null,
    model_name text not null default '',
    prompt_version text not null default '',
    input_tokens integer not null default 0,
    output_tokens integer not null default 0,
    estimated_cost real not null default 0,
    status text not null default 'logged',
    created_at text not null default current_timestamp
);

create table if not exists campus_schedule_rules (
    id integer generated by default as identity primary key,
    rule_key text not null unique,
    role_group text not null default 'all',
    action_type text not null,
    location text not null default '',
    start_hour integer not null default 0,
    end_hour integer not null default 24,
    weekday_pattern text not null default 'all',
    min_exam_pressure integer not null default 0,
    max_exam_pressure integer not null default 100,
    base_weight real not null default 1.0,
    noise real not null default 0.15,
    description text not null default '',
    status text not null default 'active',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists world_causal_weights (
    id integer generated by default as identity primary key,
    weight_key text not null unique,
    source_metric text not null,
    target_type text not null,
    target_key text not null,
    direction real not null default 1.0,
    strength real not null default 1.0,
    threshold real not null default 0.0,
    noise real not null default 0.1,
    description text not null default '',
    status text not null default 'active',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists experiment_runs (
    id integer generated by default as identity primary key,
    experiment_id text not null default '',
    run_id text not null unique,
    experiment_name text not null default '',
    hypothesis text not null default '',
    control_or_treatment text not null default 'natural',
    intervention_type text not null default '',
    start_time text not null default current_timestamp,
    end_time text not null default '',
    random_seed text not null default '',
    environment_version text not null default '',
    agent_config_version text not null default '',
    model_config_version text not null default '',
    world_rules_version text not null default 'world-runtime-v1',
    status text not null default 'running',
    metadata_json text not null default '{}',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists world_snapshots (
    id integer generated by default as identity primary key,
    run_id text not null default '',
    snapshot_type text not null default 'manual_checkpoint',
    world_time text not null default '',
    day integer not null default 0,
    tick_id integer references world_ticks(id) on delete set null,
    reason text not null default '',
    state_json text not null default '{}',
    schema_version text not null default 'research-v1',
    created_at text not null default current_timestamp
);

create table if not exists research_export_jobs (
    id integer generated by default as identity primary key,
    run_id text not null default '',
    export_format text not null default 'both',
    export_path text not null default '',
    status text not null default 'running',
    started_at text not null default current_timestamp,
    completed_at text not null default '',
    metadata_json text not null default '{}',
    quality_report_json text not null default '{}'
);

create table if not exists calibration_observations (
    id integer generated by default as identity primary key,
    source_name text not null default '',
    observed_at text not null default '',
    metric_name text not null,
    metric_value real not null,
    location text not null default '',
    role_group text not null default '',
    sample_size integer not null default 0,
    metadata_json text not null default '{}',
    created_at text not null default current_timestamp
);

create table if not exists calibration_reports (
    id integer generated by default as identity primary key,
    report_key text not null unique,
    run_id text not null default '',
    generated_at text not null default current_timestamp,
    summary text not null default '',
    parameter_updates text not null default '{}',
    quality_report_json text not null default '{}'
);

insert into simulation_state (key, value)
values ('current_day', '1'), ('campus_initialized', '0')
on conflict (key) do nothing;

insert into campus_spaces
    (code, name, location, capacity, open_hour, close_hour, status, crowd_field, purpose)
values
    ('dorm', '宿舍区', '宿舍区', 600, 0, 24, '开放', 'dorm_crowd', '休息、社交与夜间生活'),
    ('teaching', '教学楼', '教学楼', 450, 7, 22, '开放', 'classroom_crowd', '上课、小组讨论与实验'),
    ('library', '图书馆', '图书馆', 220, 8, 22, '开放', 'library_crowd', '自习、阅读与研究'),
    ('canteen', '食堂', '食堂', 300, 6, 21, '开放', 'canteen_crowd', '用餐与日常交流'),
    ('playground', '操场', '操场', 500, 6, 22, '开放', 'playground_crowd', '运动、训练与大型活动'),
    ('business', '商业街', '商业街', 180, 9, 22, '开放', 'commercial_crowd', '消费、创业与服务'),
    ('admin', '校务处', '校务处', 80, 8, 18, '开放', 'campus_flow', '通知、管理与政策协商')
on conflict (code) do nothing;

insert into campus_schedule_rules
    (rule_key, role_group, action_type, location, start_hour, end_hour, weekday_pattern, min_exam_pressure, max_exam_pressure, base_weight, noise, description)
values
    ('student_deep_night_rest', 'student', 'rest', '宿舍区', 0, 6, 'all', 0, 100, 9.0, 0.10, '学生深夜以宿舍休息为主'),
    ('student_breakfast', 'student', 'consume', '食堂', 6, 9, 'all', 0, 100, 4.0, 0.25, '早餐时段学生更可能去食堂'),
    ('student_morning_class', 'student', 'attend_class', '教学楼', 8, 12, 'weekday', 0, 100, 7.0, 0.18, '工作日上午课程活动'),
    ('student_noon_queue', 'student', 'queue', '食堂', 11, 13, 'all', 0, 100, 5.0, 0.30, '午餐高峰排队'),
    ('student_exam_study', 'student', 'observe', '图书馆', 18, 23, 'all', 65, 100, 6.0, 0.20, '考试压力高时晚间自习增加'),
    ('student_evening_club', 'student', 'club_activity', '操场', 18, 21, 'all', 0, 70, 3.2, 0.35, '晚间社团与运动活动'),
    ('teacher_morning_class', 'teacher', 'attend_class', '教学楼', 8, 12, 'weekday', 0, 100, 6.5, 0.15, '教师上午授课'),
    ('teacher_office_hour', 'teacher', 'collaborate', '校务处', 14, 17, 'weekday', 0, 100, 3.5, 0.20, '教师下午处理教务协作'),
    ('business_lunch_service', 'business', 'consume', '食堂', 10, 14, 'all', 0, 100, 4.5, 0.25, '商户午间服务'),
    ('business_shop_hours', 'business', 'consume', '商业街', 9, 22, 'all', 0, 100, 6.0, 0.22, '商业街营业时段'),
    ('service_morning_patrol', 'service', 'observe', '校务处', 7, 10, 'all', 0, 100, 4.5, 0.18, '后勤早间巡查'),
    ('service_crowd_support', 'service', 'collaborate', '食堂', 11, 13, 'all', 0, 100, 3.6, 0.25, '后勤午间协调拥挤')
on conflict (rule_key) do nothing;

insert into world_causal_weights
    (weight_key, source_metric, target_type, target_key, direction, strength, threshold, noise, description)
values
    ('rain_reduces_playground', 'rainfall', 'location', '操场', -1.0, 0.75, 25, 0.12, '降雨降低操场吸引力'),
    ('rain_increases_library', 'rainfall', 'location', '图书馆', 1.0, 0.25, 25, 0.10, '降雨增加室内学习倾向'),
    ('exam_increases_library', 'exam_pressure', 'location', '图书馆', 1.0, 0.70, 60, 0.10, '考试压力增加图书馆密度'),
    ('exam_increases_teaching', 'exam_pressure', 'location', '教学楼', 1.0, 0.35, 60, 0.10, '考试压力增加教学楼学习活动'),
    ('activity_increases_playground', 'activity_heat', 'location', '操场', 1.0, 0.45, 60, 0.18, '活动热度提高操场活动概率'),
    ('resource_pressure_increases_queue', 'resource_pressure', 'action', 'queue', 1.0, 0.65, 60, 0.12, '资源压力提高排队和等待行为'),
    ('crowd_increases_conflict', 'campus_flow', 'action', 'conflict', 1.0, 0.20, 75, 0.18, '拥挤提高小冲突概率'),
    ('study_mood_increases_collaboration', 'study_atmosphere', 'action', 'collaborate', 1.0, 0.28, 65, 0.14, '学习氛围提升协作概率')
on conflict (weight_key) do nothing;

create index if not exists idx_agent_learning_resident_day on agent_learning(resident_id, day);
create index if not exists idx_agent_news_posts_day on agent_news_posts(day);
create index if not exists idx_campus_events_day_status on campus_events(day, status);
create index if not exists idx_city_events_day_id on city_events(day, id desc);
create index if not exists idx_external_information_category on external_information(category);
create index if not exists idx_group_goals_status_deadline on group_goals(status, deadline_day);
create index if not exists idx_memories_resident_day on memories(resident_id, day);
create index if not exists idx_simulation_action_logs_resident_day on simulation_action_logs(resident_id, day);
create index if not exists idx_relationship_change_events_pair_day on relationship_change_events(from_resident_id, to_resident_id, day);
create index if not exists idx_simulation_action_logs_resident_id_desc on simulation_action_logs(resident_id, id desc);
create index if not exists idx_relationship_change_events_pair_id_desc on relationship_change_events(from_resident_id, to_resident_id, id desc);
create index if not exists idx_agent_goals_resident_horizon_status on agent_goals(resident_id, horizon, status);
create index if not exists idx_agent_goals_parent on agent_goals(parent_goal_id);
create index if not exists idx_goal_dependencies_goal on goal_dependencies(goal_id, relationship_type);
create index if not exists idx_goal_revisions_goal_day on goal_revisions(goal_id, day);
create index if not exists idx_agent_commitments_resident_status_due on agent_commitments(resident_id, status, due_at);
create index if not exists idx_plan_outcomes_resident_day on plan_outcomes(resident_id, day);
create index if not exists idx_plan_outcomes_plan on plan_outcomes(plan_id, step_key);
create unique index if not exists idx_plan_outcomes_unique_step on plan_outcomes(plan_id, step_key);
create index if not exists idx_trajectory_episodes_resident_horizon on trajectory_episodes(resident_id, horizon, status);
create index if not exists idx_trajectory_episodes_goal on trajectory_episodes(goal_id);
create unique index if not exists idx_trajectory_episodes_unique_goal on trajectory_episodes(resident_id, goal_id, horizon);
create index if not exists idx_world_ticks_started_at on world_ticks(started_at);
create index if not exists idx_world_event_stream_created_at on world_event_stream(created_at);
create index if not exists idx_world_event_stream_event_type on world_event_stream(event_type);
create index if not exists idx_world_event_stream_resident_id on world_event_stream(resident_id);
create index if not exists idx_world_event_stream_resident_day on world_event_stream(resident_id, day);
create index if not exists idx_world_event_stream_tick_id on world_event_stream(tick_id);
create index if not exists idx_agent_action_plans_window on agent_action_plans(window_start, window_end);
create index if not exists idx_observer_sessions_last_seen on observer_sessions(last_seen_at);
create index if not exists idx_model_call_logs_trigger_date on model_call_logs(trigger_type, created_at);
create index if not exists idx_campus_schedule_rules_context on campus_schedule_rules(role_group, action_type, start_hour, end_hour);
create index if not exists idx_world_causal_weights_source on world_causal_weights(source_metric, target_type);
create index if not exists idx_experiment_runs_run_id on experiment_runs(run_id);
create index if not exists idx_experiment_runs_status on experiment_runs(status);
create index if not exists idx_world_snapshots_run_id on world_snapshots(run_id);
create index if not exists idx_world_snapshots_created_at on world_snapshots(created_at);
create index if not exists idx_research_export_jobs_run_id on research_export_jobs(run_id);
create index if not exists idx_research_export_jobs_started_at on research_export_jobs(started_at);
create index if not exists idx_calibration_observations_metric on calibration_observations(metric_name, observed_at);
create index if not exists idx_calibration_reports_run_id on calibration_reports(run_id);

insert into agent_goals
    (resident_id, legacy_long_term_goal_id, horizon, title, category, source,
     priority, commitment, expected_utility, feasibility, uncertainty,
     deadline_at, status, progress, visibility, created_day, last_reviewed_day,
     created_at, completed_at)
select
    resident_id, id, 'long', title, category, 'legacy_migration',
    70, 65, 70, 55, 35,
    'simulation-day:' || deadline_day, status, progress, 'private', 1,
    last_update_day, created_at, completed_at
from long_term_goals
on conflict (legacy_long_term_goal_id) do nothing;

-- Spatial Foundation & Open-World Realism (Phase 3.6 & Spatial Runtime)

create table if not exists spatial_nodes (
    id integer generated by default as identity primary key,
    world_key text not null default 'default',
    code text not null unique,
    name text not null,
    node_type text not null,
    parent_id integer references spatial_nodes(id) on delete set null,
    x real not null,
    y real not null,
    z real not null,
    radius real not null default 1.0,
    capacity integer not null default 50,
    status text not null default 'open',
    longitude real,
    latitude real,
    elevation_m real not null default 0,
    geometry_json text,
    source_element_id text,
    properties text not null default '{}',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists spatial_edges (
    id integer generated by default as identity primary key,
    from_node_id integer not null references spatial_nodes(id) on delete cascade,
    to_node_id integer not null references spatial_nodes(id) on delete cascade,
    distance_meters real not null,
    base_minutes real not null,
    bidirectional boolean not null default true,
    status text not null default 'open',
    congestion_factor real not null default 1.0,
    weather_factor real not null default 1.0,
    properties text not null default '{}',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists agent_spatial_capabilities (
    resident_id integer primary key references residents(id) on delete cascade,
    base_speed_m_per_min real not null default 75.0,
    mobility_class text not null default 'pedestrian',
    accessibility_needs text not null default 'none',
    perception_radius_m real not null default 30.0,
    hearing_radius_m real not null default 15.0,
    source text not null default 'rule-based-v1',
    version text not null default 'spatial-v1',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists agent_spatial_states (
    resident_id integer primary key references residents(id) on delete cascade,
    world_key text not null default 'default',
    current_node_id integer not null references spatial_nodes(id),
    target_node_id integer references spatial_nodes(id) on delete set null,
    movement_status text not null default 'idle',
    path_nodes_json text not null default '[]',
    current_path_index integer not null default 0,
    progress_meters real not null default 0.0,
    step_distance_meters real not null default 0.0,
    elapsed_seconds integer not null default 0,
    estimated_duration_seconds integer not null default 0,
    last_arrival_at text not null default '',
    last_departure_at text not null default '',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp
);

create table if not exists agent_trajectories (
    id integer generated by default as identity primary key,
    resident_id integer not null references residents(id) on delete cascade,
    experiment_run_id integer,
    branch_key text not null default 'main',
    tick_number integer not null,
    world_time text not null,
    node_id integer not null references spatial_nodes(id),
    movement_status text not null,
    progress_ratio real not null default 0.0,
    created_at text not null default current_timestamp
);

create table if not exists spatial_resources (
    id integer generated by default as identity primary key,
    node_id integer not null references spatial_nodes(id) on delete cascade,
    resource_key text not null,
    name text not null,
    capacity integer not null default 10,
    occupied integer not null default 0,
    status text not null default 'open',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp,
    unique(node_id, resource_key)
);

create table if not exists spatial_admission_queue (
    id integer generated by default as identity primary key,
    node_id integer not null references spatial_nodes(id) on delete cascade,
    resource_id integer references spatial_resources(id) on delete set null,
    resident_id integer not null references residents(id) on delete cascade,
    queue_position integer not null,
    status text not null default 'waiting',
    joined_at text not null default current_timestamp,
    updated_at text not null default current_timestamp,
    unique(node_id, resident_id)
);

create table if not exists spatial_import_batches (
    id integer generated by default as identity primary key,
    batch_key text not null unique,
    world_key text not null,
    source text not null,
    license text not null,
    original_crs text not null default 'EPSG:4326',
    projection_meta text not null default '{}',
    nodes_count integer not null default 0,
    edges_count integer not null default 0,
    imported_at text not null default current_timestamp
);

create table if not exists spatial_affordances (
    id integer generated by default as identity primary key,
    world_key text not null default 'default',
    node_id integer not null references spatial_nodes(id) on delete cascade,
    affordance_key text not null,
    name text not null,
    requirements text not null default '{}',
    effects text not null default '{}',
    capacity integer not null default 0,
    status text not null default 'open',
    created_at text not null default current_timestamp,
    updated_at text not null default current_timestamp,
    unique(node_id, affordance_key)
);

create index if not exists ix_spatial_nodes_world_key on spatial_nodes(world_key);
create index if not exists ix_spatial_edges_from_node on spatial_edges(from_node_id);
create index if not exists ix_spatial_edges_to_node on spatial_edges(to_node_id);
create index if not exists ix_agent_spatial_states_current_node on agent_spatial_states(current_node_id);
create index if not exists ix_agent_trajectories_resident_tick on agent_trajectories(resident_id, tick_number);
create index if not exists ix_spatial_import_batches_world_key on spatial_import_batches(world_key);
create index if not exists ix_spatial_affordances_world on spatial_affordances(world_key);
